/* Ribbon command handlers — generated by scripts/gen-ribbon.py. Do not edit. */
import {
  align,
  distribute,
} from "../lib/alignment";
import {
  matchSize,
  stretchToEdge,
  straightenLines,
  fillGap,
  unifyShapes,
} from "../lib/sizePosition";
import {
  selectSame,
} from "../lib/selectSame";
import {
  setSelectedShapesVisible,
  showAllShapes,
} from "../lib/visibility";
import {
  setAutoSize,
  setWordWrap,
  setMargins,
  setParagraphAlignment,
  clearLineBreaks,
  clearText,
  setBullets,
  applyTextStyle,
  mergeText,
  splitText,
} from "../lib/text";
import {
  swapPosition,
  swapSize,
  swapFillAndOutline,
  pickUpSizePosition,
  applySizePosition,
  applyToMatchingObjects,
} from "../lib/transform";
import {
  addTableRow,
  addTableColumn,
  deleteLastTableRow,
  deleteLastTableColumn,
  tableToText,
} from "../lib/tables";
import {
  insertSpecialShape,
} from "../lib/specialShapes";
import {
  insertTableOfContents,
  addStickyNote,
} from "../lib/slides";

const RUNNERS: Record<string, () => Promise<void>> = {
  alignLeft: () => align("left", "selection"),
  alignCenter: () => align("centerH", "selection"),
  alignRight: () => align("right", "selection"),
  alignTop: () => align("top", "selection"),
  alignMiddle: () => align("middle", "selection"),
  alignBottom: () => align("bottom", "selection"),
  distributeH: () => distribute("horizontal"),
  distributeV: () => distribute("vertical"),
  matchWidth: () => matchSize("width", "last"),
  matchHeight: () => matchSize("height", "last"),
  matchSizeBoth: () => matchSize("both", "last"),
  stretchLeft: () => stretchToEdge("left", "selection"),
  stretchRight: () => stretchToEdge("right", "selection"),
  stretchTop: () => stretchToEdge("top", "selection"),
  stretchBottom: () => stretchToEdge("bottom", "selection"),
  fillGapH: () => fillGap("horizontal"),
  fillGapV: () => fillGap("vertical"),
  unifySize: () => unifyShapes(),
  straightenLines: () => straightenLines(),
  selectFill: () => selectSame("fillColor"),
  selectOutline: () => selectSame("lineColor"),
  selectWeight: () => selectSame("lineWeight"),
  selectFont: () => selectSame("fontName"),
  selectType: () => selectSame("shapeType"),
  selectSize: () => selectSame("size"),
  selectPosTop: () => selectSame("positionTop"),
  selectPosLeft: () => selectSame("positionLeft"),
  selectPosRight: () => selectSame("positionRight"),
  selectPosBottom: () => selectSame("positionBottom"),
  hideShapes: () => setSelectedShapesVisible(false),
  showShapes: () => showAllShapes(),
  autofitOn: () => setAutoSize(PowerPoint.ShapeAutoSize.autoSizeShapeToFitText),
  autofitOff: () => setAutoSize(PowerPoint.ShapeAutoSize.autoSizeNone),
  wrapOn: () => setWordWrap(true),
  wrapOff: () => setWordWrap(false),
  marginsNone: () => setMargins({ left: 0, right: 0, top: 0, bottom: 0 }),
  marginsNarrow: () => setMargins({ left: 3.6, right: 3.6, top: 3.6, bottom: 3.6 }),
  marginsNormal: () => setMargins({ left: 7.2, right: 7.2, top: 3.6, bottom: 3.6 }),
  marginsWide: () => setMargins({ left: 14.4, right: 14.4, top: 14.4, bottom: 14.4 }),
  alignTextLeft: () => setParagraphAlignment(PowerPoint.ParagraphHorizontalAlignment.left),
  alignTextCenter: () => setParagraphAlignment(PowerPoint.ParagraphHorizontalAlignment.center),
  alignTextRight: () => setParagraphAlignment(PowerPoint.ParagraphHorizontalAlignment.right),
  alignTextJustify: () => setParagraphAlignment(PowerPoint.ParagraphHorizontalAlignment.justify),
  bulletsOn: () => setBullets(true),
  bulletsOff: () => setBullets(false),
  clearBreaks: () => clearLineBreaks(),
  clearTextRibbon: () => clearText(),
  mergeTextRibbon: () => mergeText(),
  splitTextRibbon: () => splitText(),
  styleHeading: () => applyTextStyle({ name: "Noto Sans", size: 12, bold: true }),
  styleSubheading: () => applyTextStyle({ name: "Noto Sans", size: 12, bold: false }),
  styleBody: () => applyTextStyle({ name: "Noto Sans", size: 12, bold: false }),
  swapPositionRibbon: () => swapPosition(),
  swapSizeRibbon: () => swapSize(),
  swapFillRibbon: () => swapFillAndOutline(),
  pickUpRibbon: () => pickUpSizePosition(),
  applySizeRibbon: () => applySizePosition(),
  applyMatchingRibbon: () => applyToMatchingObjects(),
  addTableRowRibbon: () => addTableRow(),
  addTableColumnRibbon: () => addTableColumn(),
  deleteTableRowRibbon: () => deleteLastTableRow(),
  deleteTableColumnRibbon: () => deleteLastTableColumn(),
  tableToTextRibbon: () => tableToText(),
  specialTitle: () => insertSpecialShape("title"),
  specialConclusion: () => insertSpecialShape("conclusion"),
  specialFootnote: () => insertSpecialShape("footnote"),
  specialGhost: () => insertSpecialShape("ghost"),
  specialLabel: () => insertSpecialShape("label"),
  insertTocRibbon: () => insertTableOfContents(),
  addNoteRibbon: () => addStickyNote(""),
};

Office.onReady(() => undefined);

for (const [name, run] of Object.entries(RUNNERS)) {
  Office.actions.associate(name, (event: Office.AddinCommands.Event) => {
    run()
      .catch((error) => console.error(`StudioTools: ${name} failed`, error))
      .finally(() => event.completed());
  });
}
